version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80" # Porta do host mapeada para a porta do contêiner
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cliente_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
